version: 2
jobs:
  build:
    docker:
      - image: matehat/erlang-and-cassandra
        command: ["/bin/bash"]

    environment:
      JVM_OPTS: "-Xmn200M -Xms300M -Xmx512M"

    steps:
      - checkout
      - run:
          name: Run Cassandra
          command: cassandra -R -f
          background: true
      
      - restore_cache:
          key: rebar-deps-{{ checksum "/opt/cqerl/rebar.lock" }}
      
      - run:
          name: Build
          command: rebar3 compile
        
      - save_cache:
          key: rebar-deps-{{ checksum "/opt/cqerl/rebar.lock" }}
          paths:
            - /opt/cqerl/_build

      - run:
          name: Common Test
          command: rebar3 ct --sys_config=test/test.config
