version: 2
jobs:
  build:
    docker:
      - image: matehat/erlang-and-cassandra
    steps:
      - checkout
      - run:
          name: Build
          command: rebar3 compile
      - run:
          name: Common Test
          command: rebar3 ct --sys_config=test/test.config
